### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by mkurz** [schaloner/deadbolt-2-scala#13]
Hi @schaloner,

is it possible that you git-tag your releases? It's easier to compare/diff tags to see what has changed between versions. Also for deadbolt-java please :smile: 
Thanks!

**Comment by schaloner** [comment]
Done for 2.4.0 and 2.4.0.1, will occur on a rolling basis for future releases.

**Comment by mkurz** [comment]
@schaloner Thanks!
