### ISSUE TITLE
How to inject DeadboltActions in a Play Controller that depends on it ?

### ISSUE THREAD

**Issue by sdiwu** [schaloner/deadbolt-2-scala#16]
Let's say I have Play 2.4 Controller like this:

    class Application @Inject() (deadbolt: DeadboltActions, myService: MyService) extends Controller {
    
      def hello = deadbolt.SubjectPresent() {
        Action.async{
          val res = myService.helloWorld
          res.map(s => Ok(s))
        }
      }
    }

And I use compile time dependency injection to inject the `Application` controller:
https://www.playframework.com/documentation/2.4.x/ScalaCompileTimeDependencyInjection

Here is my application loader:

    class MyAplicationLoader extends ApplicationLoader {
      def load(context: Context): Application = {
        new MyComponents(context).application
      }
    }
    
    class MyComponents(context: Context) extends BuiltInComponentsFromContext(context)  {
      lazy val myService = new MyService()
    
      // The issue is at here. How do I inject the DeadboltActions to Application controller?
      lazy val applicationController = new controllers.Application(..., myService)
    
      lazy val assets = new controllers.Assets(httpErrorHandler)
      lazy val router = new Routes(httpErrorHandler, applicationController, assets)
    }

As you can see the code, at this line I need to provide the `DeadboltActions` argument to the `Application` controller:

    lazy val applicationController = new controllers.Application(..., myService)

I don't know how to instantiate`DeadboltActions`, I checked the `DeadboltActions` has this signature:

    class DeadboltActions(analyzer: be.objectify.deadbolt.scala.ScalaAnalyzer, handlers: be.objectify.deadbolt.scala.cache.HandlerCache)

I can supply  `HandlerCache` argument with `MyHandlerCache` but don't know about `ScalaAnalyzer`.

**Comment by schaloner** [comment]
If you check the bindings in [DeadboltModule](https://github.com/schaloner/deadbolt-2-scala/blob/master/code/app/be/objectify/deadbolt/scala/DeadboltModule.scala#L12-L13) you can see  `ScalaAnalwer` is bound to itself.  It's stateless, so you can just create a new one to pass into `DeadboltActions`.

~~~
// get cacheApi via Play
lazy val patternCache = new DefaultPatternCache(cacheApi)
lazy val scalaAnalyzer = new ScalaAnalyzer(patternCache)
lazy val deadboltActions = new DeadboltActions(scalaAnalyzer, handlerCache)
lazy val applicationController = new controllers.Application(deadboltActions, myService)
~~~

If you don't want to use `CacheApi`, you can implement your own `PatternCache` and have it always compile the pattern; e.g.

~~~
class NoneCachingPatternCache extends PatternCache {
  override def apply(value: String): Option[Pattern] = Some(Pattern.compile(value))
}
~~~

**Comment by sdiwu** [comment]
Hi, thank you for the solution.

Probably if it's better if you could make a helper method to simply this, or maybe a trait component like:

	class MyComponents(context: Context) extends BuiltInComponentsFromContext(context) with DeadBoltComponents  {
	  lazy val myService = new MyService()
	
	  lazy val applicationController = new controllers.Application(deadboltActions, myService)
	  ...

The `DeadBoltComponents` trait would contain the `deadboltActions` variable that I can just direclty use it.

**Comment by schaloner** [comment]
Good idea.  It'll be in the next release.

**Comment by schaloner** [comment]
Available in `"be.objectify" %% "deadbolt-scala" % "2.4.2"` - add the `DeadboltComponents` trait to get started.
