### ISSUE TITLE
user present or not using AuthenticatedRequest in templates

### ISSUE THREAD

**Issue by diadys** [schaloner/deadbolt-2-scala#20]
Hi,

I try to migrate to 2.5 but I have a blocking question:

I have templates using deadbolt views (e.g. @subjectNotPresentOr(){} {}) rendered sometimes with a subject present, sometimes not. That means I call my template from a Play standard Action.
Hence, I manually have to create an AuthenticatedRequest to pass it to the template.

Is there a better option than this not very pretty workaround? Or a maybeSubject action could be interesting in that use case ?

Thanks a lot.

Cheers.

**Comment by schaloner** [comment]
So at the moment, you're using something like this?

    def index= Action { request =>
      Ok(myTemplate(AuthenticatedRequest(request, None)))
    }

**Comment by diadys** [comment]
That's the idea: a slightly more complex as I use my user cache service to retrieve it from the play session if exists and pass it to the AuthenticatedRequest constructor.

**Comment by schaloner** [comment]
Something like [this](https://github.com/schaloner/deadbolt-2-scala/pull/21)?

**Comment by schaloner** [comment]
It's done.  See

* https://github.com/schaloner/deadbolt-2-scala/blob/master/code/app/be/objectify/deadbolt/scala/ActionBuilders.scala#L88
* https://github.com/schaloner/deadbolt-2-scala/blob/master/code/app/be/objectify/deadbolt/scala/DeadboltActions.scala#L187

**Comment by diadys** [comment]
Awesome ! much clearer and factorized in deadbolt code !

Many thanks !

**Comment by schaloner** [comment]
Any other ideas for improvements, or issues with the migration?

**Comment by diadys** [comment]
nope, migration was pretty smooth, that's great !

**Comment by schaloner** [comment]
If you have a public project or product and are willing to be featured on the Deadbolt website, let me know!
