### ISSUE TITLE
Deadbolt Website is down

### ISSUE THREAD

**Issue by knightpop** [schaloner/deadbolt-2-scala#30]
I want to read documentation about deadbolt2 but it`s down.
https://deadbolt-scala.readme.io/

can you update the address??

**Comment by schaloner** [comment]
The domains are managed by http://readme.io - this is a problem on their side.  Interestingly, https://deadbolt-java.readme.io/ is working correctly.  I'll get in touch and find out what's happening.  

Thanks for letting me know!

**Comment by schaloner** [comment]
Reported to readme.io at 09:40 GMT+2.

**Comment by schaloner** [comment]
The answer:
"In theory, ReadMe is up and running... but we are having some random DNS issues. I'm not sure exactly what the problem is, but we're looking into it now. I'll let you know when we have more information."

Also, kudos to readme.io for the fast response!

**Comment by schaloner** [comment]
More info from readme.io:
"Okay, a bit more info! All .io domains are having DNS issues currently. Seems it's time to either cough up money for readme.com, or get people to memorize our IP address :)

Not much we can do (blah), but we will be around until it's fixed.

-Greg"

If anyone wants to spring for the paid version, let me know :-)

**Comment by schaloner** [comment]
It's working correctly again.

**Comment by knightpop** [comment]
@schaloner Oh! working correctly Thanks!
