### ISSUE TITLE
Pubilsh 2.7.1 with play 2.7.3 and scala 2.13 support

### ISSUE THREAD

**Issue by whyoleg** [schaloner/deadbolt-2-scala#50]
Is the last version with play 2.7.3 and scala 2.13 support going to ever be published to maven repos?

Thank you.

**Comment by mkurz** [comment]
Ping @schaloner

**Comment by louisjiang** [comment]
Support for scala 2.13?

**Comment by mkurz** [comment]
Unfortunately @schaloner is not responding lately... Hopefully he sees this message...

**Comment by mkurz** [comment]
2.7.1 released with Scala 2.13 support: http://repo1.maven.org/maven2/be/objectify/deadbolt-scala_2.13/2.7.1/
