### ISSUE TITLE
Can't find artifacts for deadbolt-scala 2.7.1 for scala 2.11

### ISSUE THREAD

**Issue by countfloyd** [schaloner/deadbolt-2-scala#51]
Maven central has a directory for deadbolt-scala_2.11 2.7.1 but nothing in it, except for a java doc asc file.

**Comment by mkurz** [comment]
We are working towards a new release. I will let you now when that happened.

**Comment by mkurz** [comment]
Here it is now: https://repo1.maven.org/maven2/be/objectify/deadbolt-scala_2.11/2.7.1/
