### ISSUE TITLE
Accessing Deadbolt user from within Controller for Scala

### ISSUE THREAD

**Issue by n0tel** [schaloner/deadbolt-2-scala#8]
How i can get User from within Controller?

Is it possible to access this user in my controllers to avoid retrieving the user twice per request?

I have found this question, but he did not answer the question for Scala.
http://stackoverflow.com/questions/16857677/accessing-deadbolt-user-from-within-controller

**Comment by schaloner** [comment]
This is addressed in from 2.4.4 onwards
